In [8]:
import pandas as pd
import emoji
import re
from tqdm.notebook import tqdm as tqdm

In [9]:

df = pd.read_csv("tweets1.csv") 

# extracts emojis
def extract_emojis(text):
    return [char for char in text if char in emoji.EMOJI_DATA]

# new 'emojis' column
df['emojis_present'] = df['Text'].apply(extract_emojis)

In [10]:
df

                                                     Text   emojis_present
0                   He is right.. there was/is no chaos 🤡              [🤡]
1                                 Oooh. A manly man 🤡🤡😂😂😂  [🤡, 🤡, 😂, 😂, 😂]
2       But Gavi is the problem and Bernabeu senior pl...  [🤡, 🤡, 🤡, 🤡, 🤡]
3             feel like i have two personalities lately 🤡              [🤡]
4                                               To late 🤡              [🤡]
...                                                   ...              ...
157781  I take immense pride in washing dishes, pots, ...              [✅]
157782                                       Time to ✅✅✅✅     [✅, ✅, ✅, ✅]
157783                                 Happy Easter 🐣 ❤️✅        [🐣, ❤, ✅]
157784  Happy Easter everyone! Duty for today: Easter ...              [✅]
157785      Yoghurt is the best way to clear a hangover ✅              [✅]

[157786 rows x 2 columns]

In [11]:
from itertools import chain

all_emojis = list(set(chain.from_iterable(df['emojis_present'])))
all_emojis.sort()  #for consistency
emoji_dict = {e: i for i, e in enumerate(all_emojis)}

In [12]:
emoji_dict

{'©': 0,
 '®': 1,
 '‼': 2,
 '⁉': 3,
 '™': 4,
 'ℹ': 5,
 '↔': 6,
 '⌚': 7,
 '⌛': 8,
 '⌨': 9,
 '⏩': 10,
 '⏪': 11,
 '⏯': 12,
 '⏰': 13,
 '⏱': 14,
 '⏲': 15,
 '⏳': 16,
 '⏸': 17,
 '⏹': 18,
 'Ⓜ': 19,
 '▪': 20,
 '▫': 21,
 '◼': 22,
 '◽': 23,
 '◾': 24,
 '☀': 25,
 '☁': 26,
 '☂': 27,
 '☃': 28,
 '☄': 29,
 '☎': 30,
 '☑': 31,
 '☔': 32,
 '☕': 33,
 '☘': 34,
 '☝': 35,
 '☠': 36,
 '☢': 37,
 '☣': 38,
 '☦': 39,
 '☪': 40,
 '☮': 41,
 '☯': 42,
 '☹': 43,
 '☺': 44,
 '♀': 45,
 '♂': 46,
 '♈': 47,
 '♉': 48,
 '♊': 49,
 '♋': 50,
 '♌': 51,
 '♎': 52,
 '♏': 53,
 '♐': 54,
 '♑': 55,
 '♒': 56,
 '♓': 57,
 '♟': 58,
 '♠': 59,
 '♣': 60,
 '♥': 61,
 '♦': 62,
 '♨': 63,
 '♻': 64,
 '♾': 65,
 '♿': 66,
 '⚒': 67,
 '⚓': 68,
 '⚔': 69,
 '⚕': 70,
 '⚖': 71,
 '⚙': 72,
 '⚠': 73,
 '⚡': 74,
 '⚧': 75,
 '⚪': 76,
 '⚫': 77,
 '⚰': 78,
 '⚱': 79,
 '⚽': 80,
 '⚾': 81,
 '⛄': 82,
 '⛅': 83,
 '⛈': 84,
 '⛏': 85,
 '⛓': 86,
 '⛔': 87,
 '⛪': 88,
 '⛰': 89,
 '⛱': 90,
 '⛲': 91,
 '⛳': 92,
 '⛴': 93,
 '⛵': 94,
 '⛷': 95,
 '⛸': 96,
 '⛹': 97,
 '⛺': 98,
 '⛽': 99,
 '✂': 100,
 '✅': 101,
 '✈': 102,
 '✉': 103,
 '✊': 104,
 '✋': 105,
 '✌': 106,
 '✍': 107,
 '✏': 108,
 '✒': 109,
 '✔': 110,
 '✖': 111,
 '✝': 112,
 '✡': 113,
 '✨': 114,
 '✳': 115,
 '✴': 116,
 '❄': 117,
 '❇': 118,
 '❌': 119,
 '❎': 120,
 '❓': 121,
 '❔': 122,
 '❕': 123,
 '❗': 124,
 '❣': 125,
 '❤': 126,
 '➕': 127,
 '➗': 128,
 '➡': 129,
 '➰': 130,
 '➿': 131,
 '⤴': 132,
 '⤵': 133,
 '⬆': 134,
 '⬇': 135,
 '⬛': 136,
 '⭐': 137,
 '⭕': 138,
 '〰': 139,
 '〽': 140,
 '㊗': 141,
 '🀄': 142,
 '🃏': 143,
 '🅰': 144,
 '🅱': 145,
 '🅾': 146,
 '🅿': 147,
 '🆎': 148,
 '🆑': 149,
 '🆒': 150,
 '🆔': 151,
 '🆕': 152,
 '🆗': 153,
 '🆘': 154,
 '🆙': 155,
 '🈴': 156,
 '🈵': 157,
 '🈶': 158,
 '🉐': 159,
 '🌀': 160,
 '🌁': 161,
 '🌃': 162,
 '🌄': 163,
 '🌅': 164,
 '🌆': 165,
 '🌇': 166,
 '🌈': 167,
 '🌉': 168,
 '🌊': 169,
 '🌋': 170,
 '🌌': 171,
 '🌍': 172,
 '🌎': 173,
 '🌏': 174,
 '🌐': 175,
 '🌑': 176,
 '🌔': 177,
 '🌕': 178,
 '🌖': 179,
 '🌗': 180,
 '🌙': 181,
 '🌚': 182,
 '🌛': 183,
 '🌜': 184,
 '🌝': 185,
 '🌞': 186,
 '🌟': 187,
 '🌠': 188,
 '🌡': 189,
 '🌤': 190,
 '🌥': 191,
 '🌦': 192,
 '🌧': 193,
 '🌨': 194,
 '🌩': 195,
 '🌪': 196,
 '🌫': 197,
 '🌬': 198,
 '🌭': 199,
 '🌮': 200,
 '🌯': 201,
 '🌰': 202,
 '🌱': 203,
 '🌲': 204,
 '🌳': 205,
 '🌴': 206,
 '🌵': 207,
 '🌶': 208,
 '🌷': 209,
 '🌸': 210,
 '🌹': 211,
 '🌺': 212,
 '🌻': 213,
 '🌼': 214,
 '🌽': 215,
 '🌾': 216,
 '🌿': 217,
 '🍀': 218,
 '🍁': 219,
 '🍂': 220,
 '🍃': 221,
 '🍄': 222,
 '🍅': 223,
 '🍆': 224,
 '🍇': 225,
 '🍈': 226,
 '🍉': 227,
 '🍊': 228,
 '🍋': 229,
 '🍌': 230,
 '🍍': 231,
 '🍎': 232,
 '🍏': 233,
 '🍐': 234,
 '🍑': 235,
 '🍒': 236,
 '🍓': 237,
 '🍔': 238,
 '🍕': 239,
 '🍖': 240,
 '🍗': 241,
 '🍘': 242,
 '🍙': 243,
 '🍚': 244,
 '🍛': 245,
 '🍜': 246,
 '🍝': 247,
 '🍞': 248,
 '🍟': 249,
 '🍠': 250,
 '🍡': 251,
 '🍢': 252,
 '🍣': 253,
 '🍤': 254,
 '🍥': 255,
 '🍦': 256,
 '🍧': 257,
 '🍨': 258,
 '🍩': 259,
 '🍪': 260,
 '🍫': 261,
 '🍬': 262,
 '🍭': 263,
 '🍮': 264,
 '🍯': 265,
 '🍰': 266,
 '🍱': 267,
 '🍲': 268,
 '🍳': 269,
 '🍴': 270,
 '🍵': 271,
 '🍷': 272,
 '🍸': 273,
 '🍹': 274,
 '🍺': 275,
 '🍻': 276,
 '🍼': 277,
 '🍽': 278,
 '🍾': 279,
 '🍿': 280,
 '🎀': 281,
 '🎁': 282,
 '🎂': 283,
 '🎃': 284,
 '🎄': 285,
 '🎅': 286,
 '🎆': 287,
 '🎇': 288,
 '🎈': 289,
 '🎉': 290,
 '🎊': 291,
 '🎋': 292,
 '🎍': 293,
 '🎐': 294,
 '🎑': 295,
 '🎒': 296,
 '🎓': 297,
 '🎖': 298,
 '🎗': 299,
 '🎙': 300,
 '🎚': 301,
 '🎛': 302,
 '🎞': 303,
 '🎟': 304,
 '🎡': 305,
 '🎢': 306,
 '🎣': 307,
 '🎤': 308,
 '🎥': 309,
 '🎦': 310,
 '🎧': 311,
 '🎨': 312,
 '🎩': 313,
 '🎪': 314,
 '🎫': 315,
 '🎬': 316,
 '🎭': 317,
 '🎮': 318,
 '🎯': 319,
 '🎰': 320,
 '🎱': 321,
 '🎲': 322,
 '🎳': 323,
 '🎵': 324,
 '🎶': 325,
 '🎷': 326,
 '🎸': 327,
 '🎹': 328,
 '🎺': 329,
 '🎻': 330,
 '🎼': 331,
 '🎾': 332,
 '🏀': 333,
 '🏁': 334,
 '🏂': 335,
 '🏃': 336,
 '🏄': 337,
 '🏅': 338,
 '🏆': 339,
 '🏇': 340,
 '🏈': 341,
 '🏉': 342,
 '🏊': 343,
 '🏋': 344,
 '🏌': 345,
 '🏍': 346,
 '🏎': 347,
 '🏏': 348,
 '🏐': 349,
 '🏒': 350,
 '🏓': 351,
 '🏔': 352,
 '🏕': 353,
 '🏖': 354,
 '🏗': 355,
 '🏘': 356,
 '🏙': 357,
 '🏚': 358,
 '🏛': 359,
 '🏜': 360,
 '🏝': 361,
 '🏞': 362,
 '🏟': 363,
 '🏠': 364,
 '🏡': 365,
 '🏢': 366,
 '🏣': 367,
 '🏤': 368,
 '🏥': 369,
 '🏦': 370,
 '🏨': 371,
 '🏩': 372,
 '🏪': 373,
 '🏫': 374,
 '🏬': 375,
 '🏭': 376,
 '🏯': 377,
 '🏰': 378,
 '🏳': 379,
 '🏴': 380,
 '🏵': 381,
 '🏷': 382,
 '🏹': 383,
 '🏻': 384,
 '🏼': 385,
 '🏽': 386,
 '🏾': 387,
 '🏿': 388,
 '🐀': 389,
 '🐁': 390,
 '🐂': 391,
 '🐃': 392,
 '🐄': 393,
 '🐅': 394,
 '🐆': 395,
 '🐇': 396,
 '🐈': 397,
 '🐉': 398,
 '🐊': 399,
 '🐋': 400,
 '🐌': 401,
 '🐍': 402,
 '🐎': 403,
 '🐏': 404,
 '🐐': 405,
 '🐑': 406,
 '🐒': 407,
 '🐓': 408,
 '🐔': 409,
 '🐕': 410,
 '🐖': 411,
 '🐗': 412,
 '🐘': 413,
 '🐙': 414,
 '🐚': 415,
 '🐛': 416,
 '🐜': 417,
 '🐝': 418,
 '🐞': 419,
 '🐟': 420,
 '🐠': 421,
 '🐡': 422,
 '🐢': 423,
 '🐣': 424,
 '🐤': 425,
 '🐥': 426,
 '🐦': 427,
 '🐧': 428,
 '🐨': 429,
 '🐩': 430,
 '🐪': 431,
 '🐬': 432,
 '🐭': 433,
 '🐮': 434,
 '🐯': 435,
 '🐰': 436,
 '🐱': 437,
 '🐲': 438,
 '🐳': 439,
 '🐴': 440,
 '🐵': 441,
 '🐶': 442,
 '🐷': 443,
 '🐸': 444,
 '🐹': 445,
 '🐺': 446,
 '🐻': 447,
 '🐼': 448,
 '🐽': 449,
 '🐾': 450,
 '🐿': 451,
 '👀': 452,
 '👁': 453,
 '👂': 454,
 '👃': 455,
 '👄': 456,
 '👅': 457,
 '👆': 458,
 '👇': 459,
 '👈': 460,
 '👉': 461,
 '👊': 462,
 '👋': 463,
 '👌': 464,
 '👍': 465,
 '👎': 466,
 '👏': 467,
 '👐': 468,
 '👑': 469,
 '👒': 470,
 '👓': 471,
 '👔': 472,
 '👕': 473,
 '👖': 474,
 '👗': 475,
 '👘': 476,
 '👙': 477,
 '👚': 478,
 '👛': 479,
 '👜': 480,
 '👞': 481,
 '👟': 482,
 '👠': 483,
 '👢': 484,
 '👣': 485,
 '👤': 486,
 '👥': 487,
 '👦': 488,
 '👧': 489,
 '👨': 490,
 '👩': 491,
 '👪': 492,
 '👫': 493,
 '👬': 494,
 '👭': 495,
 '👮': 496,
 '👯': 497,
 '👰': 498,
 '👱': 499,
 '👲': 500,
 '👳': 501,
 '👴': 502,
 '👵': 503,
 '👶': 504,
 '👷': 505,
 '👸': 506,
 '👹': 507,
 '👺': 508,
 '👻': 509,
 '👼': 510,
 '👽': 511,
 '👾': 512,
 '👿': 513,
 '💀': 514,
 '💁': 515,
 '💂': 516,
 '💃': 517,
 '💄': 518,
 '💅': 519,
 '💆': 520,
 '💇': 521,
 '💈': 522,
 '💉': 523,
 '💊': 524,
 '💋': 525,
 '💌': 526,
 '💍': 527,
 '💎': 528,
 '💐': 529,
 '💑': 530,
 '💒': 531,
 '💓': 532,
 '💔': 533,
 '💕': 534,
 '💖': 535,
 '💗': 536,
 '💘': 537,
 '💙': 538,
 '💚': 539,
 '💛': 540,
 '💜': 541,
 '💝': 542,
 '💞': 543,
 '💟': 544,
 '💠': 545,
 '💡': 546,
 '💢': 547,
 '💣': 548,
 '💤': 549,
 '💥': 550,
 '💦': 551,
 '💧': 552,
 '💨': 553,
 '💩': 554,
 '💪': 555,
 '💫': 556,
 '💬': 557,
 '💭': 558,
 '💮': 559,
 '💯': 560,
 '💰': 561,
 '💱': 562,
 '💲': 563,
 '💳': 564,
 '💴': 565,
 '💵': 566,
 '💶': 567,
 '💷': 568,
 '💸': 569,
 '💹': 570,
 '💺': 571,
 '💻': 572,
 '💼': 573,
 '💽': 574,
 '💾': 575,
 '💿': 576,
 '📀': 577,
 '📄': 578,
 '📈': 579,
 '📉': 580,
 '📊': 581,
 '📌': 582,
 '📍': 583,
 '📏': 584,
 '📐': 585,
 '📑': 586,
 '📒': 587,
 '📖': 588,
 '📗': 589,
 '📘': 590,
 '📙': 591,
 '📚': 592,
 '📛': 593,
 '📜': 594,
 '📝': 595,
 '📞': 596,
 '📟': 597,
 '📠': 598,
 '📡': 599,
 '📢': 600,
 '📣': 601,
 '📥': 602,
 '📦': 603,
 '📧': 604,
 '📨': 605,
 '📩': 606,
 '📫': 607,
 '📬': 608,
 '📰': 609,
 '📱': 610,
 '📲': 611,
 '📳': 612,
 '📴': 613,
 '📶': 614,
 '📷': 615,
 '📸': 616,
 '📹': 617,
 '📺': 618,
 '📻': 619,
 '📼': 620,
 '📽': 621,
 '📿': 622,
 '🔁': 623,
 '🔂': 624,
 '🔃': 625,
 '🔄': 626,
 '🔅': 627,
 '🔆': 628,
 '🔇': 629,
 '🔈': 630,
 '🔊': 631,
 '🔋': 632,
 '🔌': 633,
 '🔍': 634,
 '🔎': 635,
 '🔏': 636,
 '🔐': 637,
 '🔑': 638,
 '🔒': 639,
 '🔓': 640,
 '🔔': 641,
 '🔕': 642,
 '🔖': 643,
 '🔗': 644,
 '🔘': 645,
 '🔙': 646,
 '🔚': 647,
 '🔛': 648,
 '🔜': 649,
 '🔝': 650,
 '🔞': 651,
 '🔟': 652,
 '🔢': 653,
 '🔥': 654,
 '🔦': 655,
 '🔧': 656,
 '🔨': 657,
 '🔩': 658,
 '🔪': 659,
 '🔫': 660,
 '🔬': 661,
 '🔭': 662,
 '🔮': 663,
 '🔯': 664,
 '🔰': 665,
 '🔱': 666,
 '🔴': 667,
 '🔵': 668,
 '🔶': 669,
 '🔹': 670,
 '🔺': 671,
 '🔻': 672,
 '🕉': 673,
 '🕊': 674,
 '🕌': 675,
 '🕎': 676,
 '🕒': 677,
 '🕙': 678,
 '🕚': 679,
 '🕛': 680,
 '🕜': 681,
 '🕝': 682,
 '🕠': 683,
 '🕣': 684,
 '🕦': 685,
 '🕯': 686,
 '🕳': 687,
 '🕴': 688,
 '🕵': 689,
 '🕶': 690,
 '🕷': 691,
 '🕸': 692,
 '🕹': 693,
 '🕺': 694,
 '🖇': 695,
 '🖊': 696,
 '🖋': 697,
 '🖌': 698,
 '🖍': 699,
 '🖐': 700,
 '🖕': 701,
 '🖖': 702,
 '🖤': 703,
 '🖲': 704,
 '🖼': 705,
 '🗂': 706,
 '🗃': 707,
 '🗑': 708,
 '🗒': 709,
 '🗓': 710,
 '🗝': 711,
 '🗞': 712,
 '🗡': 713,
 '🗣': 714,
 '🗨': 715,
 '🗯': 716,
 '🗳': 717,
 '🗺': 718,
 '🗽': 719,
 '🗾': 720,
 '🗿': 721,
 '😀': 722,
 '😁': 723,
 '😂': 724,
 '😃': 725,
 '😄': 726,
 '😅': 727,
 '😆': 728,
 '😇': 729,
 '😈': 730,
 '😉': 731,
 '😊': 732,
 '😋': 733,
 '😌': 734,
 '😍': 735,
 '😎': 736,
 '😏': 737,
 '😐': 738,
 '😑': 739,
 '😒': 740,
 '😓': 741,
 '😔': 742,
 '😕': 743,
 '😖': 744,
 '😗': 745,
 '😘': 746,
 '😙': 747,
 '😚': 748,
 '😛': 749,
 '😜': 750,
 '😝': 751,
 '😞': 752,
 '😟': 753,
 '😠': 754,
 '😡': 755,
 '😢': 756,
 '😣': 757,
 '😤': 758,
 '😥': 759,
 '😦': 760,
 '😧': 761,
 '😨': 762,
 '😩': 763,
 '😪': 764,
 '😫': 765,
 '😬': 766,
 '😭': 767,
 '😮': 768,
 '😯': 769,
 '😰': 770,
 '😱': 771,
 '😲': 772,
 '😳': 773,
 '😴': 774,
 '😵': 775,
 '😶': 776,
 '😷': 777,
 '😸': 778,
 '😹': 779,
 '😺': 780,
 '😻': 781,
 '😼': 782,
 '😽': 783,
 '😾': 784,
 '😿': 785,
 '🙀': 786,
 '🙁': 787,
 '🙂': 788,
 '🙃': 789,
 '🙄': 790,
 '🙅': 791,
 '🙆': 792,
 '🙇': 793,
 '🙈': 794,
 '🙉': 795,
 '🙊': 796,
 '🙋': 797,
 '🙌': 798,
 '🙍': 799,
 '🙎': 800,
 '🙏': 801,
 '🚀': 802,
 '🚁': 803,
 '🚂': 804,
 '🚆': 805,
 '🚌': 806,
 '🚑': 807,
 '🚒': 808,
 '🚓': 809,
 '🚔': 810,
 '🚕': 811,
 '🚖': 812,
 '🚗': 813,
 '🚘': 814,
 '🚙': 815,
 '🚚': 816,
 '🚛': 817,
 '🚜': 818,
 '🚠': 819,
 '🚢': 820,
 '🚤': 821,
 '🚥': 822,
 '🚦': 823,
 '🚨': 824,
 '🚩': 825,
 '🚪': 826,
 '🚫': 827,
 '🚬': 828,
 '🚭': 829,
 '🚮': 830,
 '🚰': 831,
 '🚲': 832,
 '🚴': 833,
 '🚶': 834,
 '🚹': 835,
 '🚻': 836,
 '🚽': 837,
 '🚾': 838,
 '🚿': 839,
 '🛀': 840,
 '🛁': 841,
 '🛂': 842,
 '🛅': 843,
 '🛋': 844,
 '🛌': 845,
 '🛍': 846,
 '🛎': 847,
 '🛏': 848,
 '🛐': 849,
 '🛑': 850,
 '🛒': 851,
 '🛕': 852,
 '🛖': 853,
 '🛜': 854,
 '🛞': 855,
 '🛟': 856,
 '🛠': 857,
 '🛡': 858,
 '🛢': 859,
 '🛣': 860,
 '🛤': 861,
 '🛩': 862,
 '🛫': 863,
 '🛬': 864,
 '🛰': 865,
 '🛳': 866,
 '🛴': 867,
 '🛶': 868,
 '🛸': 869,
 '🛹': 870,
 '🛺': 871,
 '🟠': 872,
 '🟡': 873,
 '🟢': 874,
 '🟣': 875,
 '🟥': 876,
 '🟦': 877,
 '🟨': 878,
 '🟩': 879,
 '🟪': 880,
 '🤌': 881,
 '🤍': 882,
 '🤎': 883,
 '🤏': 884,
 '🤐': 885,
 '🤑': 886,
 '🤒': 887,
 '🤓': 888,
 '🤔': 889,
 '🤕': 890,
 '🤖': 891,
 '🤗': 892,
 '🤘': 893,
 '🤙': 894,
 '🤚': 895,
 '🤛': 896,
 '🤜': 897,
 '🤝': 898,
 '🤞': 899,
 '🤟': 900,
 '🤠': 901,
 '🤡': 902,
 '🤢': 903,
 '🤣': 904,
 '🤤': 905,
 '🤥': 906,
 '🤦': 907,
 '🤧': 908,
 '🤨': 909,
 '🤩': 910,
 '🤪': 911,
 '🤫': 912,
 '🤬': 913,
 '🤭': 914,
 '🤮': 915,
 '🤯': 916,
 '🤰': 917,
 '🤱': 918,
 '🤲': 919,
 '🤳': 920,
 '🤴': 921,
 '🤵': 922,
 '🤶': 923,
 '🤷': 924,
 '🤸': 925,
 '🤹': 926,
 '🤺': 927,
 '🤼': 928,
 '🤾': 929,
 '🤿': 930,
 '🥀': 931,
 '🥁': 932,
 '🥂': 933,
 '🥃': 934,
 '🥄': 935,
 '🥅': 936,
 '🥇': 937,
 '🥈': 938,
 '🥉': 939,
 '🥊': 940,
 '🥋': 941,
 '🥌': 942,
 '🥎': 943,
 '🥐': 944,
 '🥑': 945,
 '🥒': 946,
 '🥓': 947,
 '🥔': 948,
 '🥕': 949,
 '🥖': 950,
 '🥗': 951,
 '🥘': 952,
 '🥙': 953,
 '🥚': 954,
 '🥛': 955,
 '🥜': 956,
 '🥝': 957,
 '🥞': 958,
 '🥟': 959,
 '🥡': 960,
 '🥢': 961,
 '🥣': 962,
 '🥤': 963,
 '🥥': 964,
 '🥦': 965,
 '🥧': 966,
 '🥨': 967,
 '🥩': 968,
 '🥪': 969,
 '🥫': 970,
 '🥬': 971,
 '🥭': 972,
 '🥮': 973,
 '🥯': 974,
 '🥰': 975,
 '🥱': 976,
 '🥲': 977,
 '🥳': 978,
 '🥴': 979,
 '🥵': 980,
 '🥶': 981,
 '🥷': 982,
 '🥸': 983,
 '🥹': 984,
 '🥺': 985,
 '🥻': 986,
 '🥼': 987,
 '🥽': 988,
 '🥾': 989,
 '🦀': 990,
 '🦁': 991,
 '🦂': 992,
 '🦃': 993,
 '🦄': 994,
 '🦅': 995,
 '🦆': 996,
 '🦇': 997,
 '🦈': 998,
 '🦉': 999,
 ...}

In [18]:
import numpy as np

def multi_hot_encode(emoji_list):
    vec = np.zeros(len(emoji_dict), dtype=int)
    for e in emoji_list:
        if e in emoji_dict:
            vec[emoji_dict[e]] = 1
    return vec

df['emojis'] = df['emojis_present'].apply(multi_hot_encode)

In [19]:
df

,Text,emojis_present,emojis
0,He is right.. there was/is no chaos 🤡,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,Oooh. A manly man 🤡🤡😂😂😂,"[🤡, 🤡, 😂, 😂, 😂]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,But Gavi is the problem and Bernabeu senior pl...,"[🤡, 🤡, 🤡, 🤡, 🤡]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,feel like i have two personalities lately 🤡,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,To late 🤡,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...
157781,"I take immense pride in washing dishes, pots, ...",[✅],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157782,Time to ✅✅✅✅,"[✅, ✅, ✅, ✅]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157783,Happy Easter 🐣 ❤️✅,"[🐣, ❤, ✅]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157784,Happy Easter everyone! Duty for today: Easter ...,[✅],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157785,Yoghurt is the best way to clear a hangover ✅,[✅],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [20]:
# remove emojis from text (tweet)
def remove_emojis(text):
    return ''.join(char for char in text if not emoji.is_emoji(char))


df['Text'] = df['Text'].apply(remove_emojis)

In [24]:
df

,Text,emojis_present,emojis
0,He is right.. there was/is no chaos,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,Oooh. A manly man,"[🤡, 🤡, 😂, 😂, 😂]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,But Gavi is the problem and Bernabeu senior pl...,"[🤡, 🤡, 🤡, 🤡, 🤡]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,feel like i have two personalities lately,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,To late,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...
157781,"I take immense pride in washing dishes, pots, ...",[✅],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157782,Time to,"[✅, ✅, ✅, ✅]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157783,Happy Easter ️,"[🐣, ❤, ✅]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157784,Happy Easter everyone! Duty for today: Easter ...,[✅],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
157785,Yoghurt is the best way to clear a hangover,[✅],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [26]:
from transformers import pipeline

classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k=None)

Device set to use mps:0

In [42]:

df2 = pd.read_csv("tweets1.csv")  # Replace with your actual dataframe

# Function to get emotion probabilities for each tweet
def get_emotion_probs(text):
    emotion_scores = classifier(text)
    # Extract only the probabilities for each emotion
    return {score['label']: score['score'] for score in emotion_scores[0]}

tqdm.pandas()
# Apply function to the 'Text' column and create new columns for each emotion
emotion_columns = ['anger', 'disgust', 'fear', 'joy', 'neutral', 'sadness', 'surprise']
for emotion in tqdm(emotion_columns):
    df2[emotion] = df2['Text'].progress_apply(lambda x: get_emotion_probs(x).get(emotion, 0))

# Preview the dataframe
print(df2.head())

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/157786 [00:00<?, ?it/s]

  0%|          | 0/157786 [00:00<?, ?it/s]

  0%|          | 0/157786 [00:00<?, ?it/s]

  0%|          | 0/157786 [00:00<?, ?it/s]

  0%|          | 0/157786 [00:00<?, ?it/s]

  0%|          | 0/157786 [00:00<?, ?it/s]

  0%|          | 0/157786 [00:00<?, ?it/s]

                                                Text     anger   disgust  \
0              He is right.. there was/is no chaos 🤡  0.040665  0.009426
1                            Oooh. A manly man 🤡🤡😂😂😂  0.006647  0.007574
2  But Gavi is the problem and Bernabeu senior pl...  0.037219  0.012868
3        feel like i have two personalities lately 🤡  0.007147  0.004734
4                                          To late 🤡  0.015996  0.008235

       fear       joy   neutral   sadness  surprise
0  0.044908  0.013053  0.780378  0.101912  0.009658
1  0.009317  0.298752  0.038402  0.013841  0.625466
2  0.711041  0.003013  0.116199  0.112439  0.007220
3  0.026335  0.637733  0.066424  0.247558  0.010069
4  0.007065  0.009124  0.455880  0.459994  0.043706

In [34]:
# Get the first tweet
first_tweet = df['Text'].iloc[5049]

# Run emotion classifier on that tweet
emotion_scores = classifier(first_tweet)

# Format the output
emotion_dict = {score['label']: score['score'] for score in emotion_scores[0]}

# Print results
print(f"Tweet: {first_tweet}\n")
print("Emotion scores:")
for emotion, score in emotion_dict.items():
    print(f"{emotion}: {score:.4f}")

Tweet: kiss on top of head is just *chef’s kiss*

Emotion scores:
disgust: 0.5859
anger: 0.1645
fear: 0.1523
neutral: 0.0653
sadness: 0.0188
joy: 0.0107
surprise: 0.0025

In [44]:
df2[:1]

,Text,anger,disgust,fear,joy,neutral,sadness,surprise
0,He is right.. there was/is no chaos 🤡,0.040665,0.009426,0.044908,0.013053,0.780378,0.101912,0.009658

In [45]:
df2.to_csv("tweet_with_emotion.csv", index=False)

In [46]:
df.head()

,Text,emojis_present,emojis
0,He is right.. there was/is no chaos,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,Oooh. A manly man,"[🤡, 🤡, 😂, 😂, 😂]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,But Gavi is the problem and Bernabeu senior pl...,"[🤡, 🤡, 🤡, 🤡, 🤡]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,feel like i have two personalities lately,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,To late,[🤡],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [47]:
df2.head()

,Text,anger,disgust,fear,joy,neutral,sadness,surprise
0,He is right.. there was/is no chaos 🤡,0.040665,0.009426,0.044908,0.013053,0.780378,0.101912,0.009658
1,Oooh. A manly man 🤡🤡😂😂😂,0.006647,0.007574,0.009317,0.298752,0.038402,0.013841,0.625466
2,But Gavi is the problem and Bernabeu senior pl...,0.037219,0.012868,0.711041,0.003013,0.116199,0.112439,0.007220
3,feel like i have two personalities lately 🤡,0.007147,0.004734,0.026335,0.637733,0.066424,0.247558,0.010069
4,To late 🤡,0.015996,0.008235,0.007065,0.009124,0.455880,0.459994,0.043706

In [49]:
df_with_emoji_emotion = pd.concat([df, df2.drop(columns=['Text'])], axis=1)

In [65]:
df_with_emoji_emotion.to_csv("tweet_with_emoji_emotion.csv", index=False)

In [70]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
from scipy.special import softmax
import torch

# pipeline setup
MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
config = AutoConfig.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)


def preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

# Sentiment probability extractor
def get_sentiment_probs(text):
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt', truncation=True, max_length=512)
    with torch.no_grad():
        output = model(**encoded_input)
    scores = output.logits[0].numpy()
    scores = softmax(scores)
    return {
        'negative': float(scores[0]),
        'neutral': float(scores[1]),
        'positive': float(scores[2])
    }

# applyyy
from tqdm import tqdm
tqdm.pandas()

df_with_emoji_emotion['negative'] = df_with_emoji_emotion['Text'].progress_apply(lambda x: get_sentiment_probs(x)['negative'])
df_with_emoji_emotion['neutral_sent'] = df_with_emoji_emotion['Text'].progress_apply(lambda x: get_sentiment_probs(x)['neutral'])
df_with_emoji_emotion['positive'] = df_with_emoji_emotion['Text'].progress_apply(lambda x: get_sentiment_probs(x)['positive'])


print(df_with_emoji_emotion.head())

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
100%|██████████| 157786/157786 [2:03:56<00:00, 21.22it/s]
100%|██████████| 157786/157786 [2:39:54<00:00, 16.45it/s]
100%|██████████| 157786/157786 [2:53:42<00:00, 15.14it/s]

                                                Text   emojis_present  \
0               He is right.. there was/is no chaos               [🤡]
1                                 Oooh. A manly man   [🤡, 🤡, 😂, 😂, 😂]
2  But Gavi is the problem and Bernabeu senior pl...  [🤡, 🤡, 🤡, 🤡, 🤡]
3         feel like i have two personalities lately               [🤡]
4                                           To late               [🤡]

                                              emojis     anger   disgust  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  0.040665  0.009426
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  0.006647  0.007574
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  0.037219  0.012868
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  0.007147  0.004734
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  0.015996  0.008235

       fear       joy   neutral   sadness  surprise  negative  neutral_sent  \
0  0.044908  0.013053  0.780378  0.101912  0.009658  0.099540      0.624789
1  0.009317  0.298752  0.038402  0.013841  0.625466  0.010493      0.239988
2  0.711041  0.003013  0.116199  0.112439  0.007220  0.421943      0.552692
3  0.026335  0.637733  0.066424  0.247558  0.010069  0.564859      0.406350
4  0.007065  0.009124  0.455880  0.459994  0.043706  0.276107      0.643474

   positive
0  0.275672
1  0.749518
2  0.025365
3  0.028792
4  0.080419

In [2]:
df_with_emoji_emotion.to_csv("tweet_with_sentiment_emoji_emotion.csv", index=False)

NameError: name 'df_with_emoji_emotion' is not defined

In [3]:
df_with_emoji_emotion = pd.read_csv('tweet_with_sentiment_emoji_emotion.csv

NameError: name 'pd' is not defined

In [14]:
import pickle



with open('emoji_dict.pickle', 'wb') as f:
    pickle.dump(emoji_dict, f)